######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 7 17:22:49 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dmsclient.h mythread.h
SOURCES += dmsclient.cpp mythread.cpp testdmsclient.cpp
