######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 9 09:35:39 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dmsclient.h mythread.h ../longreader.h ../data.h ../longsender.h
SOURCES += dmsclient.cpp \
           mythread.cpp \
           testdmsclient.cpp \
           ../longreader.cpp \
           ../longsender.cpp
